apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: postgres:12.1-alpine
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"
        - name: POSTGRES_DB
          value: "movie_db_dev"
        volumeMounts:
        - name: movie-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: movie-db-storage
        persistentVolumeClaim:
          claimName: movie-db-storage

---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
  namespace: dev
spec:
  selector:
    app: movie-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-db-storage
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
